# -*- coding: utf-8 -*-
"""Publication records. Source of truth: CV updated June 26, 2026.
Each record: year, type, title, authors (PI marked with **), venue (HTML), links.
Types: journal · accepted · proceedings · preprint · abstract · other
Only links that exist in the CV (or were already on the previous site and are
noted in CONTENT_VERIFICATION.md) are included.
"""

PUBS = [
    # ---------------------------------------------------------------- 2026
    dict(year=2026, type="journal",
         title="The Influence of Recording Duration and Vigilance State on High-Frequency Oscillation Characterization in Epilepsy",
         authors="Chen, Z., Gliske, S. V., **Alsammani, A.**, Tyner, K., Das, S., Mutahr, M., Lin, J., Hegeman, G., Smith, G., Grayden, D. B., &amp; Stacey, W.",
         venue="<em>Neurology</em>, 107(2), e218225.",
         links=[("DOI", "https://doi.org/10.1212/WNL.0000000000218225")]),
    dict(year=2026, type="journal",
         title="Interpretable Machine-Learning Prognosis of Mycetoma from Routine Clinical Data",
         authors="Yousif, M. H., **Alsammani, A.**, Abdalla, M. H., Bashier, E. B. M., Mohammed, M. A. Y., Saeed, A. A., &amp; Fahal, A. H.",
         venue="<em>Transactions of The Royal Society of Tropical Medicine and Hygiene</em>, trag061.",
         links=[("DOI", "https://doi.org/10.1093/trstmh/trag061")]),
    dict(year=2026, type="journal",
         title="A Scalable Transaction Management Framework for Consistent Document-Oriented NoSQL Databases",
         authors="Alflahi, A. A. E., Mohammed, M. A. Y., &amp; **Alsammani, A.**",
         venue="<em>Information Systems</em>, 140, 102719.",
         links=[("DOI", "https://doi.org/10.1016/j.is.2026.102719")]),
    dict(year=2026, type="accepted",
         title="A Methodology for Sustainable Management of Construction Equipment Fleets: Estimating Emissions and Enhancing Environmental Performance",
         authors="Khalafalla, M., Rueda-Benavides, J., Gransberg, D. D., &amp; **Alsammani, A. A.**",
         venue="Accepted, <em>Proceedings of the Construction Research Congress (CRC 2026)</em>, San Antonio, TX. Podium presentation.",
         links=[]),
    dict(year=2026, type="proceedings",
         title="Construction Work Zone Safety: Identifying Critical Crash Factors and Patterns in Florida",
         authors="Ubaka, A., **Alsammani, A. A.**, Khalafalla, M., &amp; Regalado, D. K.",
         venue="<em>Proceedings of the Construction Research Congress 2026</em>, ASCE, San Antonio, TX. Podium presentation.",
         links=[("ASCE", "https://ascelibrary.org/doi/10.1061/9780784486993.087")]),
    dict(year=2026, type="preprint",
         title="Calibrated and Interpretable Machine Learning for ICU Mortality Prediction Using First 24-Hour Clinical Data",
         authors="**Alsammani, A.**, Johnson, M., &amp; Elrefaei, J.",
         venue="<em>medRxiv</em> preprint, posted June 2, 2026. doi:10.64898/2026.05.30.26354524.",
         links=[("medRxiv", "https://www.medrxiv.org/content/10.64898/2026.05.30.26354524v1")]),
    dict(year=2026, type="preprint",
         title="Adaptive Control and Mittag-Leffler Stability of Caputo Fractional Systems with State-Dependent Delays",
         authors="**Alsammani, A.**, &amp; Farah, G.",
         venue="arXiv:2602.07105.",
         links=[("arXiv", "https://arxiv.org/abs/2602.07105")]),
    dict(year=2026, type="preprint",
         title="A Tutorial on Symbolic Structural Identifiability Analysis of ODE Models in Julia",
         authors="**Alsammani, A. A.**",
         venue="arXiv:2605.18910.",
         links=[("arXiv", "https://arxiv.org/abs/2605.18910")]),
    dict(year=2026, type="preprint",
         title="Crash Severity Dynamics and Risk Determinants in Florida: An Integrated Statistical and Explainable Machine Learning Analysis",
         authors="**Alsammani, A.**, Khalafalla, M., &amp; Regalado, D. K.",
         venue="SSRN Working Paper 6512551.",
         links=[]),
    dict(year=2026, type="abstract",
         title="Circadian Rhythms in High Frequency Oscillations from Long-Term Intracranial EEG",
         authors="Das, S., **Alsammani, A.**, Stacey, W., &amp; Gliske, S.",
         venue="Artificial Intelligence in Epilepsy and Neurological Disorders Conference.",
         links=[]),
    dict(year=2026, type="other",
         title="Student Guidelines for Responsible Use of AI in Higher Education",
         authors="**Alsammani, A.**",
         venue="Open Science Framework (OSF).",
         links=[]),
    # ---------------------------------------------------------------- 2025
    dict(year=2025, type="journal",
         title="Impact of Vaccination Behavior on COVID-19 Dynamics and Economic Outcomes",
         authors="**Alsammani, A.**, Ngonghala, C. N., &amp; Martcheva, M.",
         venue="<em>Mathematical Biosciences and Engineering</em>, 22(9), 2300–2338.",
         links=[("DOI", "https://doi.org/10.3934/mbe.2025084")]),
    dict(year=2025, type="proceedings",
         title="Predicting Sleep Disorders Using Machine Learning: A Comparative Analysis",
         authors="Goodyear, S., &amp; **Alsammani, A.**",
         venue="<em>Proceedings of the International Conference on Computational Science and Its Applications (ICCSA 2025)</em>, pp. 106–121.",
         links=[("DOI", "https://doi.org/10.1007/978-3-031-97000-9_7")]),
    dict(year=2025, type="preprint",
         title="Cholera Transmission Dynamics with Sanitation Control Measures",
         authors="**Alsammani, A.**, Farah, G. A. M. O., Mohammed, M. A. Y., &amp; Yavuz, M.",
         venue="arXiv:2505.08873.",
         links=[("arXiv", "https://arxiv.org/abs/2505.08873")]),
    dict(year=2025, type="abstract",
         title="Patients Undergoing Intracranial EEG Monitoring Have Fragmented and Poorly Consolidated Sleep",
         authors="Shindhelm, A., Mendez, H., **Alsammani, A.**, Hegeman, G., Stacey, W., &amp; Gliske, S.",
         venue="American Epilepsy Society (AES) Annual Meeting.",
         links=[]),
    # ---------------------------------------------------------------- 2024
    dict(year=2024, type="journal",
         title="Estimation of Circular Statistics in the Presence of Measurement Bias",
         authors="**Alsammani, A.**, Stacey, W. C., &amp; Gliske, S. V.",
         venue="<em>IEEE Journal of Biomedical and Health Informatics</em>, 28(2), 1089–1100.",
         links=[("DOI", "https://doi.org/10.1109/JBHI.2023.3334684")]),
    dict(year=2024, type="proceedings",
         title="Enhancement of Database Access Performance by Improving Data Consistency in a Non-Relational Database System (NoSQL)",
         authors="Alflahi, A. A. E., Mohammed, M. A. Y., &amp; **Alsammani, A.**",
         venue="<em>Proceedings of the International Conference on Computational Science and Its Applications (ICCSA 2024)</em>, pp. 194–205.",
         links=[]),
    dict(year=2024, type="preprint",
         title="Coexistence via Trophic Cascade in Plant–Herbivore–Carnivore Systems under Intense Predation Pressure",
         authors="Mohammed, M., Mohammed, M. A. Y., **Alsammani, A.**, Bakheet, M., Hui, C., et al.",
         venue="arXiv:2408.04862.",
         links=[("arXiv", "https://arxiv.org/abs/2408.04862")]),
    # ---------------------------------------------------------------- 2023
    dict(year=2023, type="proceedings",
         title="Mathematical Analysis of Autonomous and Nonautonomous Hepatitis B Virus Transmission Models",
         authors="**Alsammani, A.**",
         venue="<em>Proceedings of the International Conference on Computational Science and Its Applications (ICCSA 2023)</em>, pp. 327–343.",
         links=[]),
    dict(year=2023, type="preprint",
         title="Stochastic Modeling and Computational Simulations of HBV Infection Dynamics",
         authors="**Alsammani, A.**",
         venue="arXiv:2308.05819.",
         links=[("arXiv", "https://arxiv.org/abs/2308.05819")]),
    # ---------------------------------------------------------------- 2022
    dict(year=2022, type="abstract",
         title="The Impact of Intracranial EEG on Sleep Is Independent of Whether a Craniotomy Was Performed",
         authors="Tyner, K., **Alsammani, A.**, Hegeman, G., Stacey, W., &amp; Gliske, S.",
         venue="SLEEP Annual Meeting.",
         links=[]),
    # ---------------------------------------------------------------- 2021
    dict(year=2021, type="abstract",
         title="Effect of Sleep Stage on High-Frequency Oscillations and Artifacts",
         authors="**Alsammani, A.**, Gliske, S., &amp; Stacey, W.",
         venue="American Epilepsy Society (AES) Annual Meeting.",
         links=[]),
    # ---------------------------------------------------------------- 2020
    dict(year=2020, type="other",
         title="Dynamical Behavior of Nonautonomous and Stochastic HBV Infection Model",
         authors="**Alsammani, A.**",
         venue="Ph.D. Dissertation, Auburn University.",
         links=[]),
    # ---------------------------------------------------------------- 2019
    dict(year=2019, type="journal",
         title="Stability Analysis of a Chemotherapy Model with Delays",
         authors="Abdulrashid, I., **Alsammani, A. A. M.**, &amp; Han, X.",
         venue="<em>Discrete and Continuous Dynamical Systems – Series B</em>, 24(3), 989–1005.",
         links=[("DOI", "https://doi.org/10.3934/dcdsb.2019002")]),
]

TYPE_LABEL = {
    "journal": "Journal article",
    "accepted": "Accepted / in press",
    "proceedings": "Conference proceedings",
    "preprint": "Preprint",
    "abstract": "Conference abstract",
    "other": "Other scholarly output",
}
